--
-- Arquivo gerado com SQLiteStudio v3.4.17 em seg jun 9 15:56:56 2025
--
-- Codificação de texto usada: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Tabela: CIDADES
CREATE TABLE IF NOT EXISTS CIDADES (ID INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, CIDADE TEXT (50), UF TEXT (2));

-- Tabela: ENTIDADES
CREATE TABLE IF NOT EXISTS ENTIDADES (ID INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, NOME TEXT (60), ID_CIDADE INTEGER REFERENCES CIDADES (ID));

-- Tabela: PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS (ID INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, DESCRICAO TEXT (50), UN TEXT (5));

-- Tabela: VENDAS
CREATE TABLE IF NOT EXISTS VENDAS (ID INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, ID_CLIENTE INTEGER REFERENCES ENTIDADES (ID), ID_PRODUTO INTEGER REFERENCES PRODUTOS (ID), QUANTIDADE NUMERIC, VALOR NUMERIC, TOTAL NUMERIC);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
